#############################################################################
# Makefile for building: ShapeMatching
# Generated by qmake (3.0) (Qt 5.5.1)
# Project:  ShapeMatching.pro
# Template: app
# Command: /Users/changxiao/Documents/Qt/5.5/clang_64/bin/qmake -spec macx-clang CONFIG+=debug CONFIG+=x86_64 -o Makefile ShapeMatching.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = 
CFLAGS        = -pipe -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.7 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -std=c++11 -stdlib=libc++ -mmacosx-version-min=10.7 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -I../Documents/Qt/5.5/clang_64/mkspecs/macx-clang
QMAKE         = /Users/changxiao/Documents/Qt/5.5/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = ShapeMatching1.0.0
DISTDIR = /Users/changxiao/ShapeMatching/.tmp/ShapeMatching1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -stdlib=libc++ -mmacosx-version-min=10.7
LIBS          = $(SUBLIBS)  
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = 

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mpoint.cpp \
		shapedescriptor.cpp \
		munkres.cpp \
		shapematching.cpp \
		test.cpp 
OBJECTS       = main.o \
		mpoint.o \
		shapedescriptor.o \
		munkres.o \
		shapematching.o \
		test.o
DIST          = ../Documents/Qt/5.5/clang_64/mkspecs/features/spec_pre.prf \
		../Documents/Qt/5.5/clang_64/mkspecs/qdevice.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/features/device_config.prf \
		../Documents/Qt/5.5/clang_64/mkspecs/common/unix.conf \
		../Documents/Qt/5.5/clang_64/mkspecs/common/mac.conf \
		../Documents/Qt/5.5/clang_64/mkspecs/common/macx.conf \
		../Documents/Qt/5.5/clang_64/mkspecs/common/sanitize.conf \
		../Documents/Qt/5.5/clang_64/mkspecs/common/gcc-base.conf \
		../Documents/Qt/5.5/clang_64/mkspecs/common/gcc-base-mac.conf \
		../Documents/Qt/5.5/clang_64/mkspecs/common/clang.conf \
		../Documents/Qt/5.5/clang_64/mkspecs/common/clang-mac.conf \
		../Documents/Qt/5.5/clang_64/mkspecs/qconfig.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dcollision.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dcollision_private.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dquickrenderer.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dquickrenderer_private.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_3drenderer.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_3drenderer_private.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_core.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_enginio.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_help.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_location.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_network.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_script.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/features/qt_functions.prf \
		../Documents/Qt/5.5/clang_64/mkspecs/features/qt_config.prf \
		../Documents/Qt/5.5/clang_64/mkspecs/macx-clang/qmake.conf \
		../Documents/Qt/5.5/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../Documents/Qt/5.5/clang_64/mkspecs/features/exclusive_builds.prf \
		../Documents/Qt/5.5/clang_64/mkspecs/features/default_pre.prf \
		../Documents/Qt/5.5/clang_64/mkspecs/features/mac/default_pre.prf \
		../Documents/Qt/5.5/clang_64/mkspecs/features/resolve_config.prf \
		../Documents/Qt/5.5/clang_64/mkspecs/features/default_post.prf \
		../Documents/Qt/5.5/clang_64/mkspecs/features/c++11.prf \
		../Documents/Qt/5.5/clang_64/mkspecs/features/mac/sdk.prf \
		../Documents/Qt/5.5/clang_64/mkspecs/features/mac/default_post.prf \
		../Documents/Qt/5.5/clang_64/mkspecs/features/mac/objective_c.prf \
		../Documents/Qt/5.5/clang_64/mkspecs/features/warn_on.prf \
		../Documents/Qt/5.5/clang_64/mkspecs/features/mac/rez.prf \
		../Documents/Qt/5.5/clang_64/mkspecs/features/testcase_targets.prf \
		../Documents/Qt/5.5/clang_64/mkspecs/features/exceptions.prf \
		../Documents/Qt/5.5/clang_64/mkspecs/features/yacc.prf \
		../Documents/Qt/5.5/clang_64/mkspecs/features/lex.prf \
		ShapeMatching.pro mpoint.h \
		shapedescriptor.h \
		munkres.h \
		matrix.h \
		shapematching.h \
		test.h main.cpp \
		mpoint.cpp \
		shapedescriptor.cpp \
		munkres.cpp \
		shapematching.cpp \
		test.cpp
QMAKE_TARGET  = ShapeMatching
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = ShapeMatching

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-g \
		-isysroot \
		/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk \
		-std=c++11 \
		-stdlib=libc++ \
		-mmacosx-version-min=10.7 \
		-Wall \
		-W



first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: ShapeMatching.pro ../Documents/Qt/5.5/clang_64/mkspecs/macx-clang/qmake.conf ../Documents/Qt/5.5/clang_64/mkspecs/features/spec_pre.prf \
		../Documents/Qt/5.5/clang_64/mkspecs/qdevice.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/features/device_config.prf \
		../Documents/Qt/5.5/clang_64/mkspecs/common/unix.conf \
		../Documents/Qt/5.5/clang_64/mkspecs/common/mac.conf \
		../Documents/Qt/5.5/clang_64/mkspecs/common/macx.conf \
		../Documents/Qt/5.5/clang_64/mkspecs/common/sanitize.conf \
		../Documents/Qt/5.5/clang_64/mkspecs/common/gcc-base.conf \
		../Documents/Qt/5.5/clang_64/mkspecs/common/gcc-base-mac.conf \
		../Documents/Qt/5.5/clang_64/mkspecs/common/clang.conf \
		../Documents/Qt/5.5/clang_64/mkspecs/common/clang-mac.conf \
		../Documents/Qt/5.5/clang_64/mkspecs/qconfig.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dcollision.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dcollision_private.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dquickrenderer.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dquickrenderer_private.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_3drenderer.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_3drenderer_private.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_core.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_enginio.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_help.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_location.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_network.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_script.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../Documents/Qt/5.5/clang_64/mkspecs/features/qt_functions.prf \
		../Documents/Qt/5.5/clang_64/mkspecs/features/qt_config.prf \
		../Documents/Qt/5.5/clang_64/mkspecs/macx-clang/qmake.conf \
		../Documents/Qt/5.5/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../Documents/Qt/5.5/clang_64/mkspecs/features/exclusive_builds.prf \
		../Documents/Qt/5.5/clang_64/mkspecs/features/default_pre.prf \
		../Documents/Qt/5.5/clang_64/mkspecs/features/mac/default_pre.prf \
		../Documents/Qt/5.5/clang_64/mkspecs/features/resolve_config.prf \
		../Documents/Qt/5.5/clang_64/mkspecs/features/default_post.prf \
		../Documents/Qt/5.5/clang_64/mkspecs/features/c++11.prf \
		../Documents/Qt/5.5/clang_64/mkspecs/features/mac/sdk.prf \
		../Documents/Qt/5.5/clang_64/mkspecs/features/mac/default_post.prf \
		../Documents/Qt/5.5/clang_64/mkspecs/features/mac/objective_c.prf \
		../Documents/Qt/5.5/clang_64/mkspecs/features/warn_on.prf \
		../Documents/Qt/5.5/clang_64/mkspecs/features/mac/rez.prf \
		../Documents/Qt/5.5/clang_64/mkspecs/features/testcase_targets.prf \
		../Documents/Qt/5.5/clang_64/mkspecs/features/exceptions.prf \
		../Documents/Qt/5.5/clang_64/mkspecs/features/yacc.prf \
		../Documents/Qt/5.5/clang_64/mkspecs/features/lex.prf \
		ShapeMatching.pro
	$(QMAKE) -spec macx-clang CONFIG+=debug CONFIG+=x86_64 -o Makefile ShapeMatching.pro
../Documents/Qt/5.5/clang_64/mkspecs/features/spec_pre.prf:
../Documents/Qt/5.5/clang_64/mkspecs/qdevice.pri:
../Documents/Qt/5.5/clang_64/mkspecs/features/device_config.prf:
../Documents/Qt/5.5/clang_64/mkspecs/common/unix.conf:
../Documents/Qt/5.5/clang_64/mkspecs/common/mac.conf:
../Documents/Qt/5.5/clang_64/mkspecs/common/macx.conf:
../Documents/Qt/5.5/clang_64/mkspecs/common/sanitize.conf:
../Documents/Qt/5.5/clang_64/mkspecs/common/gcc-base.conf:
../Documents/Qt/5.5/clang_64/mkspecs/common/gcc-base-mac.conf:
../Documents/Qt/5.5/clang_64/mkspecs/common/clang.conf:
../Documents/Qt/5.5/clang_64/mkspecs/common/clang-mac.conf:
../Documents/Qt/5.5/clang_64/mkspecs/qconfig.pri:
../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dcollision.pri:
../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dcollision_private.pri:
../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dlogic.pri:
../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dquickrenderer.pri:
../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dquickrenderer_private.pri:
../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_3drenderer.pri:
../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_3drenderer_private.pri:
../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_clucene_private.pri:
../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_core.pri:
../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_dbus.pri:
../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_declarative.pri:
../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_declarative_private.pri:
../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_designer.pri:
../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_enginio.pri:
../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_enginio_private.pri:
../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_gui.pri:
../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_help.pri:
../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_location.pri:
../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_location_private.pri:
../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_network.pri:
../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_qml.pri:
../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_quick.pri:
../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_script.pri:
../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_script_private.pri:
../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_sql.pri:
../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_svg.pri:
../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_webengine.pri:
../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_webengine_private.pri:
../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_webenginecore.pri:
../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_webkit.pri:
../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_webkit_private.pri:
../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_websockets.pri:
../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_xml.pri:
../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../Documents/Qt/5.5/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../Documents/Qt/5.5/clang_64/mkspecs/features/qt_functions.prf:
../Documents/Qt/5.5/clang_64/mkspecs/features/qt_config.prf:
../Documents/Qt/5.5/clang_64/mkspecs/macx-clang/qmake.conf:
../Documents/Qt/5.5/clang_64/mkspecs/features/spec_post.prf:
.qmake.stash:
../Documents/Qt/5.5/clang_64/mkspecs/features/exclusive_builds.prf:
../Documents/Qt/5.5/clang_64/mkspecs/features/default_pre.prf:
../Documents/Qt/5.5/clang_64/mkspecs/features/mac/default_pre.prf:
../Documents/Qt/5.5/clang_64/mkspecs/features/resolve_config.prf:
../Documents/Qt/5.5/clang_64/mkspecs/features/default_post.prf:
../Documents/Qt/5.5/clang_64/mkspecs/features/c++11.prf:
../Documents/Qt/5.5/clang_64/mkspecs/features/mac/sdk.prf:
../Documents/Qt/5.5/clang_64/mkspecs/features/mac/default_post.prf:
../Documents/Qt/5.5/clang_64/mkspecs/features/mac/objective_c.prf:
../Documents/Qt/5.5/clang_64/mkspecs/features/warn_on.prf:
../Documents/Qt/5.5/clang_64/mkspecs/features/mac/rez.prf:
../Documents/Qt/5.5/clang_64/mkspecs/features/testcase_targets.prf:
../Documents/Qt/5.5/clang_64/mkspecs/features/exceptions.prf:
../Documents/Qt/5.5/clang_64/mkspecs/features/yacc.prf:
../Documents/Qt/5.5/clang_64/mkspecs/features/lex.prf:
ShapeMatching.pro:
qmake: FORCE
	@$(QMAKE) -spec macx-clang CONFIG+=debug CONFIG+=x86_64 -o Makefile ShapeMatching.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

check: first

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

main.o: main.cpp shapedescriptor.h \
		mpoint.h \
		shapematching.h \
		munkres.h \
		matrix.h \
		matrix.cpp \
		test.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mpoint.o: mpoint.cpp mpoint.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mpoint.o mpoint.cpp

shapedescriptor.o: shapedescriptor.cpp shapedescriptor.h \
		mpoint.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o shapedescriptor.o shapedescriptor.cpp

munkres.o: munkres.cpp munkres.h \
		matrix.h \
		matrix.cpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o munkres.o munkres.cpp

shapematching.o: shapematching.cpp shapematching.h \
		munkres.h \
		matrix.h \
		matrix.cpp \
		shapedescriptor.h \
		mpoint.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o shapematching.o shapematching.cpp

test.o: test.cpp test.h \
		munkres.h \
		matrix.h \
		matrix.cpp \
		shapematching.h \
		shapedescriptor.h \
		mpoint.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o test.o test.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

